#!/usr/bin/env bash

bbduk="bin/bbmap/bbduk.sh"

outdir="output/bbduk_trim"

thorax_r1="data/NZGL02125/CA7HAANXX-2125-03-01-1_S21_L003_R1_001.fastq.gz"
thorax_r2="data/NZGL02125/CA7HAANXX-2125-03-01-1_S21_L003_R2_001.fastq.gz"

abdo_r1="data/NZGL02125/CA7HAANXX-2125-04-01-1_S22_L002_R1_001.fastq.gz"
abdo_r2="data/NZGL02125/CA7HAANXX-2125-04-01-1_S22_L002_R2_001.fastq.gz"

"${bbduk}" in="${thorax_r1}" in2="${thorax_r2}" \
    out=output/bbduk_trim/thorax_r1.fq.gz \
    out2=output/bbduk_trim/thorax_r2.fq.gz \
    ref=bin/bbmap/resources/adapters.fa \
    ktrim=r k=23 mink=11 hdist=1 tpe tbo \
    &> "${outdir}"/thorax.log.txt &

"${bbduk}" in="${abdo_r1}" in2="${abdo_r2}" \
    out=output/bbduk_trim/abdo_r1.fq.gz \
    out2=output/bbduk_trim/abdo_r2.fq.gz \
    ref=bin/bbmap/resources/adapters.fa \
    ktrim=r k=23 mink=11 hdist=1 tpe tbo \
    &> "${outdir}"/abdo.log.txt &

wait

echo "done"

exit 0
